### ISSUE TITLE
Add golangci-lint support for all Go modules in the monorepo

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/chainlink-starknet#122]
We should include all Go modules in the monorepo: https://github.com/golangci/golangci-lint/issues/828#issuecomment-658207652

_Originally posted by @krebernisak in https://github.com/smartcontractkit/chainlink-starknet/pull/121#discussion_r976162543_

**Comment by aalu1418** [comment]
completed in: https://github.com/smartcontractkit/chainlink-starknet/pull/189
