### ISSUE TITLE
Review mdbx dependency

### ISSUE THREAD

**Issue by sdrug** [smartcontractkit/chainlink-starknet#44]
Mdbx dependecy of juno package is forcing us to switch from gcc compiler to clang. This might cause problems with future integration with core that uses gcc. We need to explore opportunities to cut mdbx dependency and go back to gcc.

**Comment by archseer** [comment]
Note: We dropped Juno's RPC altogether and we only use their primitive types. The STARK curve implementation signatures did not match starknet.js/caigo/devnet.
