### ISSUE TITLE
Move OCR2 consumer example project to `/examples/contracts`

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/chainlink-starknet#46]
We should split the contracts project/s from the example projects showcasing how to use the provided contracts.

Please move the OCR2 consumer example project, currently located in `./contracts/examples/ocr2` to `./examples/contracts/aggregator-consumer`

Notice also the project rename, from `ocr2` to `aggregator-consumer`, as the OCR2 is the underlying protocol that is not exposed to the consumer. Consumers only use our `IAggregator` interface.

Additionally, during this migration, the consumer example project should remove the duplicated aggregator mock and interface contracts, and import them instead.

**Comment by qperrot** [comment]
https://github.com/smartcontractkit/chainlink-starknet/pull/48
