### ISSUE TITLE
Define naming convention for Cairo contracts, and public vs internal functions

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/chainlink-starknet#80]
Consider this discussion: https://github.com/OpenZeppelin/cairo-contracts/discussions/34

Please define a naming convention for all our Cairo contracts, and public (also consider namespaces) vs internal functions.

1. Document the convention in `/docs/contracts/code-style.md` so future contributors are aware
2. Refactor the codebase to follow the convention

**Comment by ivpavici** [comment]
cc: @taco-paco 
Last thing we talked about was being consistent with OpenZeppelin...

**Comment by ivpavici** [comment]
One more resource:
https://github.com/onlydustxyz/development-guidelines/blob/main/starknet/README.md

**Comment by ivpavici** [comment]
new resource:
https://github.com/milancermak/cairopractice/blob/master/2022-08-25-cairo-conventions/CairoConventions.md

**Comment by krebernisak** [comment]
More resources on this topic (namespaces): https://github.com/OpenZeppelin/cairo-contracts/discussions/267

**Comment by krebernisak** [comment]
More resources (OZ renaming account API): https://github.com/OpenZeppelin/cairo-contracts/pull/446/files

**Comment by krebernisak** [comment]
Related GH Issue: https://github.com/smartcontractkit/chainlink-starknet/issues/156
